In [3]:
!pip install xmltodict

Collecting xmltodict
  Downloading xmltodict-1.0.4-py3-none-any.whl.metadata (14 kB)
Downloading xmltodict-1.0.4-py3-none-any.whl (13 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-1.0.4

In [22]:
import requests
import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET
import xmltodict
import json
import pprint

# 1. API 설정
api_key = "91b89db582a8b4e32560db475314eadfb1d2cd6aa256a914a381aa06e0d7cb4e"
url = "http://apis.data.go.kr/B552584/EvCharger/getChargerInfo"
params = {
    'serviceKey' : api_key,
    'pageNo' : '1',
    'numOfRows' : '100',
    'zcode' : '29',
    'kind' : 'F0',
    # 'statId' : '28260005',
    # 'chgerId' : '02',
    'dataType' : 'xml'
}

# 2. API 호출 및 JSON 파싱
response = requests.get(url, params=params)
data = xmltodict.parse(response.text)
pprint.pprint(data)
# 3. DataFrame으로 변환

items = data['response']['body']['items']['item']
df = pd.DataFrame(items)

{'response': {'body': {'items': {'item': [{'addr': '광주광역시 광산구 하남대로 127-10',
                                           'addrDetail': 'null',
                                           'bnm': '환경부',
                                           'busiCall': '1661-9408',
                                           'busiId': 'ME',
                                           'busiNm': '환경부',
                                           'chgerId': '01',
                                           'chgerType': '06',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F002',
                                           'lastTedt': '20260306121343',
                                           'lastTsdt': '20260306114008',
                                           'lat': '35.1810177',
                                           'limitDetail': None,
                                           'limitYn': 'N',
                                           'lng': '126.8074485',
                                           'location': 'null',
                                           'maker': '채비',
                                           'method': '단독',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '50',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '2',
                                           'statId': 'ME183018',
                                           'statNm': '블루핸즈 하남현대자동차서비스',
                                           'statUpdDt': '20260306164140',
                                           'trafficYn': 'N',
                                           'useTime': '24시간 이용가능',
                                           'year': '2018',
                                           'zcode': '29',
                                           'zscode': '29200'},
                                          {'addr': '광주광역시 남구 진월동 314-1',
                                           'addrDetail': 'null',
                                           'bnm': '환경부',
                                           'busiCall': '1661-9408',
                                           'busiId': 'ME',
                                           'busiNm': '환경부',
                                           'chgerId': '01',
                                           'chgerType': '06',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F002',
                                           'lastTedt': '20260305185343',
                                           'lastTsdt': '20260305182102',
                                           'lat': '35.124734',
                                           'limitDetail': None,
                                           'limitYn': 'N',
                                           'lng': '126.8971093',
                                           'location': 'null',
                                           'maker': '채비',
                                           'method': '단독',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '50',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '2',
                                           'statId': 'ME183019',
                                           'statNm': '기아자동차 진월점',
                                           'statUpdDt': '20260306163858',
                                           'trafficYn': 'N',
                                           'useTime': '24시간 이용가능',
                                           'year': '2018',
                                           'zcode': '29',
                                           'zscode': '29155'},
                                          {'addr': '광주광역시 서구 무진대로 955',
                                           'addrDetail': '(광천동)',
                                           'bnm': '채비',
                                           'busiCall': '1522-2573',
                                           'busiId': 'CV',
                                           'busiNm': '채비',
                                           'chgerId': '01',
                                           'chgerType': '04',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F001',
                                           'lastTedt': '20260306122705',
                                           'lastTsdt': '20260306120033',
                                           'lat': '35.161593',
                                           'limitDetail': None,
                                           'limitYn': 'N',
                                           'lng': '126.8850489',
                                           'location': 'null',
                                           'maker': '채비',
                                           'method': '단독',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '320',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '2',
                                           'statId': 'CV000779',
                                           'statNm': '아우디_광주 전시장(고진모터스)',
                                           'statUpdDt': '20260306123024',
                                           'trafficYn': 'N',
                                           'useTime': '09:00~18:00',
                                           'year': '2020',
                                           'zcode': '29',
                                           'zscode': '29140'},
                                          {'addr': '광주광역시 서구 무진대로 955',
                                           'addrDetail': '(광천동)',
                                           'bnm': '채비',
                                           'busiCall': '1522-2573',
                                           'busiId': 'CV',
                                           'busiNm': '채비',
                                           'chgerId': '02',
                                           'chgerType': '04',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F001',
                                           'lastTedt': '20260206131021',
                                           'lastTsdt': '20260206131016',
                                           'lat': '35.161593',
                                           'limitDetail': None,
                                           'limitYn': 'N',
                                           'lng': '126.8850489',
                                           'location': 'null',
                                           'maker': '채비',
                                           'method': '단독',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '320',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '1',
                                           'statId': 'CV000779',
                                           'statNm': '아우디_광주 전시장(고진모터스)',
                                           'statUpdDt': '20260211105540',
                                           'trafficYn': 'N',
                                           'useTime': '09:00~18:00',
                                           'year': '2020',
                                           'zcode': '29',
                                           'zscode': '29140'},
                                          {'addr': '광주광역시 북구 북문대로 28',
                                           'addrDetail': '(운암동, 티스테이션)',
                                           'bnm': '채비',
                                           'busiCall': '1522-2573',
                                           'busiId': 'CV',
                                           'busiNm': '채비',
                                           'chgerId': '01',
                                           'chgerType': '04',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F001',
                                           'lastTedt': '20260306120334',
                                           'lastTsdt': '20260306115145',
                                           'lat': '35.1748239',
                                           'limitDetail': '티스테이션 이용과 상관없이 충전소 '
                                                          '이용 가능',
                                           'limitYn': 'N',
                                           'lng': '126.8824089',
                                           'location': '지상1층 출구 옆 주차장',
                                           'maker': '채비',
                                           'method': '동시',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '200',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '2',
                                           'statId': 'CV002343',
                                           'statNm': '티스테이션 운암점',
                                           'statUpdDt': '20260306120538',
                                           'trafficYn': 'N',
                                           'useTime': '24시간 이용가능',
                                           'year': '2023',
                                           'zcode': '29',
                                           'zscode': '29170'},
                                          {'addr': '광주광역시 북구 북문대로 28',
                                           'addrDetail': '(운암동, 티스테이션)',
                                           'bnm': '채비',
                                           'busiCall': '1522-2573',
                                           'busiId': 'CV',
                                           'busiNm': '채비',
                                           'chgerId': '02',
                                           'chgerType': '04',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F001',
                                           'lastTedt': '20260306054937',
                                           'lastTsdt': '20260306052639',
                                           'lat': '35.1748239',
                                           'limitDetail': '티스테이션 이용과 상관없이 충전소 '
                                                          '이용 가능',
                                           'limitYn': 'N',
                                           'lng': '126.8824089',
                                           'location': '지상1층 출구 옆 주차장',
                                           'maker': '채비',
                                           'method': '동시',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '200',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '2',
                                           'statId': 'CV002343',
                                           'statNm': '티스테이션 운암점',
                                           'statUpdDt': '20260306055035',
                                           'trafficYn': 'N',
                                           'useTime': '24시간 이용가능',
                                           'year': '2023',
                                           'zcode': '29',
                                           'zscode': '29170'},
                                          {'addr': '광주광역시 광산구 소촌로152번길 53-22',
                                           'addrDetail': '야외주차장',
                                           'bnm': '이카플러그',
                                           'busiCall': '1833-4577',
                                           'busiId': 'EP',
                                           'busiNm': '이카플러그',
                                           'chgerId': '01',
                                           'chgerType': '02',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F002',
                                           'lastTedt': '20240301120354',
                                           'lastTsdt': '20240229020239',
                                           'lat': '35.1582027',
                                           'limitDetail': '시설 상황에 따라 이용이 제한될 수 '
                                                          '있음',
                                           'limitYn': 'N',
                                           'lng': '126.7985033',
                                           'location': '야외주차장',
                                           'maker': '이카플러그',
                                           'method': '단독',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '7',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '9',
                                           'statId': 'EP190089',
                                           'statNm': '광산 진왕자동차공업사',
                                           'statUpdDt': '20250117133000',
                                           'trafficYn': 'N',
                                           'useTime': '24시간 이용가능/시설 상황에 따라 이용이 '
                                                      '제한될 수 있습니다',
                                           'year': '2020',
                                           'zcode': '29',
                                           'zscode': '29200'},
                                          {'addr': '광주광역시 광산구 소촌로152번길 53-22',
                                           'addrDetail': '야외주차장',
                                           'bnm': '이카플러그',
                                           'busiCall': '1833-4577',
                                           'busiId': 'EP',
                                           'busiNm': '이카플러그',
                                           'chgerId': '02',
                                           'chgerType': '02',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F002',
                                           'lastTedt': '20240508030532',
                                           'lastTsdt': '20240508030532',
                                           'lat': '35.1582027',
                                           'limitDetail': '시설 상황에 따라 이용이 제한될 수 '
                                                          '있음',
                                           'limitYn': 'N',
                                           'lng': '126.7985033',
                                           'location': '야외주차장',
                                           'maker': '이카플러그',
                                           'method': '단독',
                                           'note': None,
                                           'nowTsdt': None,
                                           'output': '7',
                                           'parkingFree': 'Y',
                                           'powerType': None,
                                           'stat': '9',
                                           'statId': 'EP190089',
                                           'statNm': '광산 진왕자동차공업사',
                                           'statUpdDt': '20250117133000',
                                           'trafficYn': 'N',
                                           'useTime': '24시간 이용가능/시설 상황에 따라 이용이 '
                                                      '제한될 수 있습니다',
                                           'year': '2020',
                                           'zcode': '29',
                                           'zscode': '29200'},
                                          {'addr': '광주광역시 광산구 송도로 301',
                                           'addrDetail': '야외주차장',
                                           'bnm': '이카플러그',
                                           'busiCall': '1833-4577',
                                           'busiId': 'EP',
                                           'busiNm': '이카플러그',
                                           'chgerId': '01',
                                           'chgerType': '02',
                                           'delDetail': None,
                                           'delYn': 'N',
                                           'floorNum': '1',
                                           'floorType': 'F',
                                           'kind': 'F0',
                                           'kindDetail': 'F001',

In [23]:
df.columns

Index(['statNm', 'statId', 'chgerId', 'chgerType', 'addr', 'addrDetail',
       'location', 'lat', 'lng', 'useTime', 'busiId', 'bnm', 'busiNm',
       'busiCall', 'stat', 'statUpdDt', 'lastTsdt', 'lastTedt', 'nowTsdt',
       'powerType', 'output', 'method', 'zcode', 'zscode', 'kind',
       'kindDetail', 'parkingFree', 'note', 'limitYn', 'limitDetail', 'delYn',
       'delDetail', 'trafficYn', 'year', 'floorNum', 'floorType', 'maker'],
      dtype='object')

In [24]:
df = df[['statNm','addr','chgerType', 'useTime']]
df.head()

              statNm                   addr chgerType      useTime
0    블루핸즈 하남현대자동차서비스  광주광역시 광산구 하남대로 127-10        06    24시간 이용가능
1          기아자동차 진월점     광주광역시 남구 진월동 314-1        06    24시간 이용가능
2  아우디_광주 전시장(고진모터스)      광주광역시 서구 무진대로 955        04  09:00~18:00
3  아우디_광주 전시장(고진모터스)      광주광역시 서구 무진대로 955        04  09:00~18:00
4          티스테이션 운암점       광주광역시 북구 북문대로 28        04    24시간 이용가능

In [20]:
df.isnull().sum()

statNm       0
addr         0
chgerType    0
useTime      0
dtype: int64

In [25]:
df = df.drop_duplicates(subset='statNm')
df

,statNm,addr,chgerType,useTime
0,블루핸즈 하남현대자동차서비스,광주광역시 광산구 하남대로 127-10,06,24시간 이용가능
1,기아자동차 진월점,광주광역시 남구 진월동 314-1,06,24시간 이용가능
2,아우디_광주 전시장(고진모터스),광주광역시 서구 무진대로 955,04,09:00~18:00
4,티스테이션 운암점,광주광역시 북구 북문대로 28,04,24시간 이용가능
6,광산 진왕자동차공업사,광주광역시 광산구 소촌로152번길 53-22,02,24시간 이용가능/시설 상황에 따라 이용이 제한될 수 있습니다
8,광산 송정점현대자동차,광주광역시 광산구 송도로 301,02,24시간 이용가능/시설 상황에 따라 이용이 제한될 수 있습니다
10,광주 한마음모터스,광주광역시 광산구 동곡로 438,02,24시간 이용가능
12,광주북구 쉐보레동광주서비스센터,광주광역시 북구 오문로 234,02,24시간 이용가능
14,㈜남하자동차,광주광역시 남구 송암로76번길 34,02,24시간 이용가능
16,대원자동차공업사,광주광역시 남구 송암로58번길 47,02,24시간 이용가능
17,에스케이정비센터,광주광역시 서구 풍서우로 170,02,24시간 이용가능
18,(주)하남자동차공업사,광주광역시 광산구 하남산단5번로 120,02,24시간 이용가능
20,(주)명성일급자동차서비스,광주광역시 광산구 사암로 799,02,24시간 이용가능
22,(주)광주자동차공업사,광주광역시 남구 송암로24번가길 14,02,24시간 이용가능
24,디제이모터스,광주광역시 광산구 북문대로 559,02,24시간 이용가능
25,(주)동양자동차정비공업사,광주광역시 남구 송암로 102,02,24시간 이용가능
27,기아검사정비서비스,광주광역시 서구 무진대로772번길 6,02,24시간 이용가능
28,제이티자동차공업사,광주광역시 광산구 평동로 1019,02,09:00~18:00
29,지엔특장모터스,광주광역시 광산구 지로길 33,02,24시간 이용가능
30,한진모터스,광주광역시 북구 경양로 166,02,24시간 이용가능
31,㈜쌍용자동차송정서비스프라자,광주광역시 광산구 송도로 123,02,24시간 이용가능
32,(주)우일1급자동차서비스,광주광역시 남구 송암로130번길 4,02,24시간 이용가능
34,기아 광주플래그십스토어 E-pit,광주광역시 서구 죽봉대로 36,04,24시간 이용가능
36,현대서부서비스(주),광주광역시 서구 풍서좌로 247,05,24시간 이용가능
39,기아자동차 광주서비스센터,광주광역시 서구 죽봉대로 36,04,24시간 이용가능
45,쉐보레서광주서비스센터,광주광역시 광산구 하남대로 127-12,02,24시간 이용가능
47,송정대양자동차공업사,광주광역시 광산구 동곡로 817,02,24시간 이용가능
48,쌍용자동차 광주중앙영업소,광주광역시 동구 필문대로 255,02,24시간 이용가능
55,현대자동차 광주하이테크센터,광주광역시 남구 송암로76번길 31,02,24시간 이용가능
56,기아 광주 서비스센터,광주광역시 서구 죽봉대로 36,02,24시간 이용가능
59,블루핸즈 빛고을현대서비스,광주광역시 광산구 풍영정길 333,04,09:00~18:00
60,광주 바른정비서비스1급,광주광역시 광산구 목련로 372-37,02,24시간 이용가능
61,광주광역시 광산구 북부현대서비스,광주광역시 광산구 도천남길 213,02,24시간 이용가능
63,광주광역시 광산구 승주모터스,광주광역시 광산구 송촌길79번길 26,02,24시간 이용가능
64,빛고을현대서비스(주),광주광역시 광산구 풍영정길 333,02,24시간 이용가능
66,스타상사,광주광역시 광산구 목련로 345-1,02,09:00~19:00
67,르노코리아자동차서비스코너 서구점,광주광역시 서구 화개중앙로 134,02,24시간 이용가능
68,현대자동차 학동대리점,광주광역시 동구 남문로 576,04,24시간 이용가능
69,현대자동차 산수지점,광주광역시 동구 필문대로 118,04,24시간 이용가능
71,기아오토큐 금호점,광주광역시 서구 금호운천길 3,02,24시간 이용가능
72,현대자동차 블루핸즈 현대서부서비스,광주광역시 서구 풍서좌로 247,04,24시간 이용가능
74,기아오토큐 남광주서비스,광주광역시 남구 송암로24번나길 7,05,24시간 이용가능
75,현대자동차 진월대리점,광주광역시 남구 서문대로 676,04,24시간 이용가능
76,기아 봉선지점,광주광역시 남구 봉선2로 81,04,24시간 이용가능
78,기아오토큐 동광주서비스,광주광역시 북구 오문로 228,05,24시간 이용가능
79,현대블루핸즈 북광주현대서비스㈜,광주광역시 북구 하서로672번길 37,04,24시간 이용가능
81,기아 호남대리점,광주광역시 광산구 목련로253번길 8,04,24시간 이용가능
82,현대블루핸즈 북부현대서비스㈜,광주광역시 광산구 도천남길 213,04,"평일08:30~18:00,토 - 13:00 ,일 휴일"
83,현대자동차 첨단대리점,광주광역시 광산구 임방울대로 789,04,24시간 이용가능
84,광주광산서비스,광주광역시 광산구 무진대로 278-6,02,24시간 이용가능