In [2]:
import requests
from bs4 import BeautifulSoup
import lxml
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# 한페이지 24, top 100 , 제목,저자,가격,리뷰,판매지수,책제목에 어느 단어가 많이 들어가는

In [17]:
#모바일IT 120권
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

total_count = 0 
all_books = []

for page in range(1,6):
    url = f'https://www.yes24.com/product/category/daybestseller?pageNumber={page}&pageSize=24&categoryNumber=001001003&type=day'
    driver.get(url)
    time.sleep(2)
    
    print(f"IT/모바일분야 '{page}'번째 페이지 도서 정보 수집을 시작합니다.\n" + "="*40)
    
    books = driver.find_elements(By.CSS_SELECTOR, 'div.itemUnit')

    time.sleep(1)
    
    for i,book in enumerate (books,1):
        title = book.find_element(By.CSS_SELECTOR, 'a.gd_name').text
        author = book.find_element(By.CSS_SELECTOR, 'span.authPub.info_auth').text
        cost = book.find_element(By.CSS_SELECTOR, 'strong.txt_num em.yes_b').text
        review_elem = book.find_elements(By.CSS_SELECTOR, 'span.rating_grade em.yes_b')
        review = review_elem[0].text if review_elem else '리뷰 없음'
        sales_volume = book.find_element(By.CSS_SELECTOR, 'span.saleNum').text

        print(f"{i}. {title}")
        print(f" *저자 : {author}")
        print(f" *가격 : {cost}")
        print(f" *리뷰 : {review}점")
        print(f" *{sales_volume}")

        total_count += 1

        d = {
            'title' : title,
            'author' : author,
            'cost' : cost,
            'review' : review,
            'sales_volume' : sales_volume
        }

        all_books.append(d)
        
driver.quit()
print("="*40 + "\n" f"총 {total_count}건 수집이 완료되었습니다!")

'1'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. 이게 되네? 제미나이 완전 미친 활용법 81제
 *저자 : 오힘찬 저
 *가격 : 21,600
 *리뷰 : 9.9점
 *판매지수 49,464
2. 혼자 공부하는 바이브 코딩 with 클로드 코드
 *저자 : 조태호 저
 *가격 : 27,000
 *리뷰 : 9.9점
 *판매지수 34,683
3. 생성형 AI 활용과 실습
 *저자 : 서지영 저
 *가격 : 22,500
 *리뷰 : 리뷰 없음점
 *판매지수 7,710
4. 피지컬 AI 메가 트렌드
 *저자 : 최홍섭, 원미르 저
 *가격 : 20,700
 *리뷰 : 9.8점
 *판매지수 18,609
5. 요즘 바이브 코딩 안티그래비티 완벽 가이드
 *저자 : 최지호 저
 *가격 : 25,200
 *리뷰 : 9.9점
 *판매지수 28,176
6. IT 세상을 만나는 컴퓨터 개론
 *저자 : 조성호 저
 *가격 : 29,000
 *리뷰 : 10.0점
 *판매지수 12,510
7. Do it! 점프 투 파이썬
 *저자 : 박응용 저
 *가격 : 19,800
 *리뷰 : 9.7점
 *판매지수 54,051
8. AI 리터러시
 *저자 : 이선종, 이창우, 강승희 저
 *가격 : 19,800
 *리뷰 : 10.0점
 *판매지수 3,174
9. 요즘 바이브 코딩 클로드 코드 완벽 가이드
 *저자 : 최지호 저
 *가격 : 21,600
 *리뷰 : 8.4점
 *판매지수 30,273
10. 컴퓨터개론
 *저자 : 김대수, 김경동 저
 *가격 : 28,000
 *리뷰 : 10.0점
 *판매지수 6,204
11. 진짜 쓰는 실무 엑셀
 *저자 : 전진권 저
 *가격 : 18,900
 *리뷰 : 9.8점
 *판매지수 83,691
12. 난생처음 컴퓨팅 사고 with 파이썬
 *저자 : 김명호 저
 *가격 : 23,000
 *리뷰 : 8.5점
 *판매지수 8,184
13. 파이썬 for Beginner
 *저자 : 우재남 저
 *가격 : 26,000
 *리뷰 : 10.0점
 *판매지수 9,216
14. 난생처음 인공지능 입문
 *저자 : 서지영 저
 *가격 : 27,000
 *리뷰 : 10.0점
 *판매지수 11,088
15. 파워 유저를 위한 파이썬 EXPRESS
 *저자 : 천인국, 천명준 저
 *가격 : 35,000
 *리뷰 : 리뷰 없음점
 *판매지수 6,918
16. 된다! 하루 만에 끝내는 제미나이 활용법
 *저자 : 권서림 저
 *가격 : 18,000
 *리뷰 : 9.8점
 *판매지수 77,334
17. AI 시대의 질문력, 프롬프트 엔지니어링
 *저자 : 류한석 저
 *가격 : 24,300
 *리뷰 : 9.5점
 *판매지수 57,738
18. AI시대의 컴퓨터 개론
 *저자 : 강환수, 조진형, 신용현, 강환일 저
 *가격 : 29,000
 *리뷰 : 8.7점
 *판매지수 9,576
19. 누구나 쉽게 AI 작사 & 작곡 with 생성형 인공지능, 챗GPT, 수노, 유디오
 *저자 : 현병욱(오땡큐), 신수진 저
 *가격 : 18,000
 *리뷰 : 9.7점
 *판매지수 18,402
20. 쉽게 배우는 운영체제
 *저자 : 조성호 저
 *가격 : 33,000
 *리뷰 : 10.0점
 *판매지수 5,352
21. 난생처음 인공지능 with 스크래치
 *저자 : 고광일 저
 *가격 : 25,000
 *리뷰 : 10.0점
 *판매지수 4,068
22. 두근두근 파이썬
 *저자 : 천인국 저
 *가격 : 25,000
 *리뷰 : 6.7점
 *판매지수 12,000
23. 된다! AI 상위 노출
 *저자 : 이중대 저
 *가격 : 17,100
 *리뷰 : 10.0점
 *판매지수 3,480
24. 만들면서 배우는 생성형 AI 첫걸음
 *저자 : 천인국, 천명준 저
 *가격 : 29,000
 *리뷰 : 리뷰 없음점
 *판매지수 5,226
'2'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. 회사에서 바로 통하는 엑셀 FOR STARTERS
 *저자 : 전미진 저
 *가격 : 15,300
 *리뷰 : 9.8점
 *판매지수 12,300
2. 딥러닝 EXPRESS
 *저자 : 천인국 저
 *가격 : 34,000
 *리뷰 : 리뷰 없음점
 *판매지수 3,684
3. C언어 Express
 *저자 : 천인국 저
 *가격 : 32,000
 *리뷰 : 9.6점
 *판매지수 19,890
4. 혼자 공부하는 컴퓨터 구조+운영체제
 *저자 : 강민철 저
 *가격 : 25,200
 *리뷰 : 9.8점
 *판매지수 15,342
5. 안티그래비티 바이브 코딩 입문
 *저자 : 박규하 저
 *가격 : 22,500
 *리뷰 : 10.0점
 *판매지수 2,184
6. 목사님, AI와 동역하시겠습니까?
 *저자 : 김시준 저
 *가격 : 19,800
 *리뷰 : 10.0점
 *판매지수 5,556
7. 맛있는 디자인 포토샵&일러스트레이터 CC 2026
 *저자 : 박정아, 윤이사라 저
 *가격 : 23,400
 *리뷰 : 10.0점
 *판매지수 7,014
8. AI 에이전트 엔지니어링
 *저자 : 마이클 알바다 저/강민혁 역
 *가격 : 28,800
 *리뷰 : 9.6점
 *판매지수 10,203
9. 3줄의 글로 수익을 만드는 스레드 운영법
 *저자 : 이동영 저
 *가격 : 18,000
 *리뷰 : 9.6점
 *판매지수 12,924
10. 회사에서 바로 통하는 실무 엑셀 파워포인트 워드&한글
 *저자 : 전미진, 이화진, 신면철 저
 *가격 : 24,300
 *리뷰 : 9.7점
 *판매지수 12,981
11. 새내기 파이썬
 *저자 : 천인국 저
 *가격 : 30,000
 *리뷰 : 10.0점
 *판매지수 4,731
12. C언어로 쉽게 풀어쓴 자료구조
 *저자 : 천인국, 공용해, 하상호 저
 *가격 : 29,000
 *리뷰 : 9.5점
 *판매지수 15,198
13. 캔바 AI
 *저자 : 신승희, 앤미디어 저
 *가격 : 21,600
 *리뷰 : 10.0점
 *판매지수 2,610
14. 5분 제미나이
 *저자 : 오종현 저
 *가격 : 21,600
 *리뷰 : 10.0점
 *판매지수 3,444
15. AI 자율학습 클로드 코드·코덱스 CLI·제미나이 CLI 완전 활용법
 *저자 : Dave Lee 저
 *가격 : 28,800
 *리뷰 : 9.7점
 *판매지수 8,034
16. 요즘 당근 AI 개발
 *저자 : 당근 팀 저
 *가격 : 19,800
 *리뷰 : 9.9점
 *판매지수 15,894
17. 된다! 조회수 터지는 유튜브 쇼츠 만들기
 *저자 : 최지영 저
 *가격 : 19,800
 *리뷰 : 9.9점
 *판매지수 36,564
18. 어서와 파이썬은 처음이지!
 *저자 : 천인국 저
 *가격 : 33,000
 *리뷰 : 10.0점
 *판매지수 3,450
19. 파이썬으로 쉽게 배우는 자료구조
 *저자 : 최영규, 천인국 저
 *가격 : 29,000
 *리뷰 : 10.0점
 *판매지수 7,800
20. 혼자 공부하는 파이썬
 *저자 : 윤인성 저
 *가격 : 19,800
 *리뷰 : 9.3점
 *판매지수 25,707
21. 정보 보안 개론
 *저자 : 양대일 저
 *가격 : 30,000
 *리뷰 : 9.9점
 *판매지수 5,250
22. 된다! 피그마 디자인 10분 레시피
 *저자 : 하이서, 김대일, 김시원, 최유빈 저
 *가격 : 25,200
 *리뷰 : 10.0점
 *판매지수 3,996
23. 누구나 아는 나만 모르는 제미나이
 *저자 : 이성원 저
 *가격 : 17,100
 *리뷰 : 9.6점
 *판매지수 16,014
24. 요즘 교사를 위한 에듀테크 5대장 : 캔바, 패들렛, 북크리에이터, 노션, 챗GPT∙제미나이
 *저자 : 안익재, 황의태 저
 *가격 : 17,820
 *리뷰 : 10.0점
 *판매지수 15,486
'3'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. AI 버블이 온다
 *저자 : 아르빈드 나라야난, 사야시 카푸르 저/강미경 역
 *가격 : 22,320
 *리뷰 : 9.9점
 *판매지수 9,972
2. 쉽게 배우는 소프트웨어 공학
 *저자 : 김치수 저
 *가격 : 33,000
 *리뷰 : 리뷰 없음점
 *판매지수 3,849
3. 유니티 교과서
 *저자 : 김은철, 기타무라 마나미 저/유세라 역
 *가격 : 29,700
 *리뷰 : 9.6점
 *판매지수 5,160
4. 한 걸음 앞선 개발자가 지금 꼭 알아야 할 클로드 코드
 *저자 : 조훈, 정찬훈 저
 *가격 : 23,400
 *리뷰 : 8.9점
 *판매지수 9,642
5. 명품 C++ Programming
 *저자 : 황기태 저
 *가격 : 34,000
 *리뷰 : 리뷰 없음점
 *판매지수 7,542
6. 도덕적인 AI
 *저자 : 월터 시넛 암스트롱, 재나 셰익 보그, 빈센트 코니처 저/박초월 역
 *가격 : 19,800
 *리뷰 : 9.8점
 *판매지수 6,048
7. 으뜸 데이터 분석과 머신러닝
 *저자 : 박동규, 강영민, 김병욱 저
 *가격 : 32,000
 *리뷰 : 리뷰 없음점
 *판매지수 2,448
8. 쉽게 배우는 C 자료구조
 *저자 : 최영규, 천인국 저
 *가격 : 29,000
 *리뷰 : 리뷰 없음점
 *판매지수 3,450
9. 처음 만나는 인공지능
 *저자 : 김대수, 김경동 저
 *가격 : 27,000
 *리뷰 : 리뷰 없음점
 *판매지수 4,572
10. 혼자 공부하는 C 언어
 *저자 : 서현우 저
 *가격 : 23,400
 *리뷰 : 9.6점
 *판매지수 14,553
11. 컴퓨터 비전과 딥러닝
 *저자 : 오일석 저
 *가격 : 39,000
 *리뷰 : 9.8점
 *판매지수 3,498
12. 시간순삭 파이썬
 *저자 : 천인국, 정영민, 최자영 공저
 *가격 : 22,500
 *리뷰 : 10.0점
 *판매지수 7,770
13. 쉽게 배우는 데이터 통신과 컴퓨터 네트워크
 *저자 : 박기현 저
 *가격 : 30,000
 *리뷰 : 10.0점
 *판매지수 5,586
14. 엑셀 2019
 *저자 : 김지연 저
 *가격 : 20,000
 *리뷰 : 10.0점
 *판매지수 5,658
15. C 언어 콘서트
 *저자 : 천인국 저
 *가격 : 27,000
 *리뷰 : 10.0점
 *판매지수 8,730
16. 알기 쉬운 알고리즘
 *저자 : 양성봉 저
 *가격 : 24,500
 *리뷰 : 9.3점
 *판매지수 2,769
17. 클로드 코드를 활용한 바이브 코딩 완벽 입문
 *저자 : 히라카와 토모히데 저/최용 역
 *가격 : 23,400
 *리뷰 : 리뷰 없음점
 *판매지수 1,902
18. 오픈클로 with GPT, 제미나이, 클로드
 *저자 : 강민혁 저
 *가격 : 19,800
 *리뷰 : 리뷰 없음점
 *판매지수 1,806
19. 네트워크 · 보안 엔지니어를 위한 챗GPT 활용 기술
 *저자 : 박진산 저
 *가격 : 24,300
 *리뷰 : 리뷰 없음점
 *판매지수 1,386
20. 자율형 AI 에이전트 서비스 구축하기
 *저자 : 정금호 저
 *가격 : 24,300
 *리뷰 : 리뷰 없음점
 *판매지수 846
21. AI 워커스: 리디자인
 *저자 : 김아람 저
 *가격 : 22,500
 *리뷰 : 10.0점
 *판매지수 1,263
22. 엔트리로 배우는 게임 만들기 This is Coding 학교편
 *저자 : 김한나, 이지은 저/KIE 기획연구실 감수
 *가격 : 12,600
 *리뷰 : 리뷰 없음점
 *판매지수 1,200
23. 엑셀로 배우는 데이터 분석
 *저자 : 박주미 저
 *가격 : 26,000
 *리뷰 : 리뷰 없음점
 *판매지수 1,698
24. 된다! 하루 만에 끝내는 챗GPT 활용법
 *저자 : 프롬프트 크리에이터 저
 *가격 : 18,000
 *리뷰 : 9.4점
 *판매지수 37,353
'4'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. Do it! LLM을 활용한 AI 에이전트 개발 입문
 *저자 : 이성용 저
 *가격 : 31,500
 *리뷰 : 9.7점
 *판매지수 19,110
2. Do it! 오토캐드 2026
 *저자 : 박한울 저
 *가격 : 26,550
 *리뷰 : 10.0점
 *판매지수 5,652
3. 혼자 공부하는 머신러닝+딥러닝
 *저자 : 박해선 저
 *가격 : 28,800
 *리뷰 : 9.7점
 *판매지수 21,327
4. 맛있는 디자인 포토샵 CC 2025
 *저자 : 윤이사라, 김신애 저
 *가격 : 22,500
 *리뷰 : 9.8점
 *판매지수 6,000
5. 와그작 파포 2021 AI+인터넷
 *저자 : 놀이교육콘텐츠랩 저
 *가격 : 12,600
 *리뷰 : 리뷰 없음점
 *판매지수 3,462
6. Wireshark로 배우는 컴퓨터 네트워크
 *저자 : 김봉한, 이재광 저
 *가격 : 39,000
 *리뷰 : 리뷰 없음점
 *판매지수 2,508
7. 밑바닥부터 시작하는 딥러닝 1
 *저자 : 사이토 고키 저/개앞맵시 역
 *가격 : 23,400
 *리뷰 : 9.2점
 *판매지수 12,582
8. 엑셀과 파워포인트 2021
 *저자 : 김지연 저
 *가격 : 24,000
 *리뷰 : 10.0점
 *판매지수 4,596
9. 파이썬 마스터
 *저자 : 김종훈, 김동건 저
 *가격 : 32,000
 *리뷰 : 리뷰 없음점
 *판매지수 3,252
10. 누구나 쉽게 배우는 인공지능 스타트 with 챗GPT
 *저자 : 박동규 저
 *가격 : 29,000
 *리뷰 : 10.0점
 *판매지수 5,076
11. 혼자 공부하는 네트워크
 *저자 : 강민철 저
 *가격 : 25,200
 *리뷰 : 9.8점
 *판매지수 11,424
12. MySQL로 배우는 데이터베이스 개론과 실습
 *저자 : 박우창, 남송휘, 이현룡 저
 *가격 : 30,000
 *리뷰 : 8.0점
 *판매지수 3,876
13. 따라하며 배우는 파이썬과 데이터 과학
 *저자 : 천인국, 박동규, 강영민 저
 *가격 : 29,000
 *리뷰 : 10.0점
 *판매지수 5,568
14. 실습과 함께하는 정보보호개론
 *저자 : 장상수 저
 *가격 : 19,000
 *리뷰 : 리뷰 없음점
 *판매지수 1,188
15. 으뜸 컴퓨터 개론
 *저자 : 박동규 저
 *가격 : 28,000
 *리뷰 : 10.0점
 *판매지수 3,306
16. 정보통신 배움터
 *저자 : 정진욱, 안성진, 김현철, 이원혁, 유수현 저
 *가격 : 31,000
 *리뷰 : 리뷰 없음점
 *판매지수 1,530
17. 회사는 엑셀을 가르쳐주지 않아요
 *저자 : 쏘피(박성희) 저
 *가격 : 16,200
 *리뷰 : 9.7점
 *판매지수 21,897
18. 데이터베이스 개론
 *저자 : 김연희 저
 *가격 : 29,000
 *리뷰 : 9.1점
 *판매지수 7,056
19. 디지털 논리회로 실험
 *저자 : 임석구, 홍경호 저
 *가격 : 25,000
 *리뷰 : 9.0점
 *판매지수 1,956
20. Perfect C
 *저자 : 강환수, 강환일, 이동규 저
 *가격 : 30,400
 *리뷰 : 7.5점
 *판매지수 8,286
21. 난생처음 파이썬 프로그래밍
 *저자 : 우재남, 최민아 저
 *가격 : 24,000
 *리뷰 : 9.3점
 *판매지수 10,545
22. 컴퓨터 활용과 실습 2019
 *저자 : 김경희, 김혜란 저
 *가격 : 25,000
 *리뷰 : 8.0점
 *판매지수 2,586
23. 파이썬 자료구조와 알고리즘 for Beginner
 *저자 : 우재남 저
 *가격 : 27,000
 *리뷰 : 9.5점
 *판매지수 2,940
24. 손에 잡히는 데이터 통신
 *저자 : 임석구 저
 *가격 : 29,000
 *리뷰 : 9.3점
 *판매지수 4,077
'5'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. 오라클로 배우는 데이터베이스 개론과 실습
 *저자 : 박우창, 남송휘, 이현룡 저
 *가격 : 29,000
 *리뷰 : 5.0점
 *판매지수 642
2. 인공지능 시대를 위한 컴퓨터 과학 개론
 *저자 : 정기철 저
 *가격 : 27,000
 *리뷰 : 리뷰 없음점
 *판매지수 2,700
3. 컴퓨터 네트워크
 *저자 : 정진욱, 안성진, 김현철, 조강홍, 유수현 공저
 *가격 : 34,000
 *리뷰 : 6.0점
 *판매지수 1,047
4. 알기 쉬운 정보보호개론
 *저자 : 히로시 유키 저 / 이재광, 전태일, 조재신 공역
 *가격 : 29,000
 *리뷰 : 8.6점
 *판매지수 3,750
5. AI의 선택을 부르는 AEO GEO 생존 전략
 *저자 : 이재홍 저
 *가격 : 17,100
 *리뷰 : 10.0점
 *판매지수 1,932
6. QA를 넘어 개발자도 알아야 할 AI 에이전트 품질 가이드
 *저자 : 정상미, 김성수 저
 *가격 : 25,200
 *리뷰 : 리뷰 없음점
 *판매지수 2,049
7. 교실로 온 ON 제미나이
 *저자 : 박찬, 김병석, 전수연, 김지용, 구현희 저 외 3명 정보 더 보기/감추기
 *가격 : 19,800
 *리뷰 : 10.0점
 *판매지수 1,758
8. 처음이지만 프로처럼 쓰는 캔바 (Canva)
 *저자 : 정다은(시재) 저
 *가격 : 27,000
 *리뷰 : 리뷰 없음점
 *판매지수 1,506
9. 우리, 프로그래머들 We, Programmers
 *저자 : 로버트 C. 마틴 저/최희철 역
 *가격 : 27,900
 *리뷰 : 9.9점
 *판매지수 3,294
10. 한 권으로 끝내는 게임 사업 게임 마케팅
 *저자 : 알로하팩토리 저
 *가격 : 31,500
 *리뷰 : 10.0점
 *판매지수 1,722
11. 광고, UX/UI, 브랜딩에 바로 쓰는 디자인 심리 108
 *저자 : 321web(미쓰이 마사유키) 저/김현미 역
 *가격 : 16,200
 *리뷰 : 10.0점
 *판매지수 3,564
12. 포토샵+일러스트레이터 CC 2026 무작정 따라하기
 *저자 : 문수민, 민지영, 앤미디어, 전은재 저
 *가격 : 23,400
 *리뷰 : 9.9점
 *판매지수 4,026
13. 명품 자바 에센셜
 *저자 : 황기태 저
 *가격 : 31,000
 *리뷰 : 리뷰 없음점
 *판매지수 2,847
14. 컨텍스트 엔지니어링으로 완성하는 AI 에이전트
 *저자 : 박경민 저
 *가격 : 27,000
 *리뷰 : 9.7점
 *판매지수 888
15. 이게 되네? 나노바나나 AI 비포&애프터 미친 활용법 71제
 *저자 : 쌩초 저
 *가격 : 16,920
 *리뷰 : 10.0점
 *판매지수 15,702
16. 따라하며 배우는 C 언어
 *저자 : 박동규 저
 *가격 : 33,000
 *리뷰 : 10.0점
 *판매지수 756
17. 멘토시리즈 일러스트레이터
 *저자 : 코리아교육그룹 교육연구소 저
 *가격 : 25,200
 *리뷰 : 10.0점
 *판매지수 2,670
18. 써니쌤과 함께 처음 시작하는 SNS 디자인 캔바
 *저자 : 써니쌤 강성은 저
 *가격 : 17,820
 *리뷰 : 10.0점
 *판매지수 9,078
19. AI 엔지니어링
 *저자 : 칩 후옌 저/변성윤 역
 *가격 : 36,000
 *리뷰 : 9.9점
 *판매지수 13,368
20. AI 캡컷
 *저자 : 민지영, 문수민, 앤미디어 저
 *가격 : 23,400
 *리뷰 : 9.9점
 *판매지수 8,328
21. CATIA(카티아) 쉽게 따라하기
 *저자 : 정경애 저
 *가격 : 28,800
 *리뷰 : 리뷰 없음점
 *판매지수 2,022
22. 벡터 데이터베이스 설계와 구축
 *저자 : 송한림 저
 *가격 : 16,020
 *리뷰 : 9.7점
 *판매지수 4,362
23. NEW 우당탕탕 컴퓨터와 친해지기
 *저자 : 놀이교육콘텐츠랩 저
 *가격 : 12,600
 *리뷰 : 리뷰 없음점
 *판매지수 3,312
24. 마법 같은 영상 제작을 위한 스마트폰 촬영 및 편집 with 캡컷
 *저자 : 김지희 저
 *가격 : 20,700
 *리뷰 : 9.9점
 *판매지수 18,540
========================================
총 120건 수집이 완료되었습니다!

In [18]:
df_120 = pd.DataFrame(all_books)
df_120.index.name = 'No'
df_120.index += 1 
df_120.to_csv('Books120.csv',encoding='utf-8-sig')
df_120.head()

                         title      author    cost review sales_volume
No
1    이게 되네? 제미나이 완전 미친 활용법 81제       오힘찬 저  21,600    9.9  판매지수 49,464
2   혼자 공부하는 바이브 코딩 with 클로드 코드       조태호 저  27,000    9.9  판매지수 34,683
3                생성형 AI 활용과 실습       서지영 저  22,500  리뷰 없음   판매지수 7,710
4                피지컬 AI 메가 트렌드  최홍섭, 원미르 저  20,700    9.8  판매지수 18,609
5      요즘 바이브 코딩 안티그래비티 완벽 가이드       최지호 저  25,200    9.9  판매지수 28,176

In [41]:
#주간베스트 30권, +할인율, 태그까지 
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
total_count = 0 
weekly_best = []

for page in range(1,3):
    url = f'https://www.yes24.com/product/category/weekbestseller?categoryNumber=001&pageNumber={page}&pageSize=24&type=week'
    driver.get(url)
    time.sleep(2)
    
    print(f"주간베스트 '{page}'번째 페이지 도서 정보 수집을 시작합니다.\n" + "="*40)
    
    books = driver.find_elements(By.CSS_SELECTOR, 'div.itemUnit')

    time.sleep(1)
    
    for i,book in enumerate (books,1):
        if total_count >= 30:
            break
        
        title = book.find_element(By.CSS_SELECTOR, 'a.gd_name').text
        author = book.find_element(By.CSS_SELECTOR, 'span.authPub.info_auth').text
        cost = book.find_element(By.CSS_SELECTOR, 'strong.txt_num em.yes_b').text
        
        sale_elem = book.find_elements(By.CSS_SELECTOR, 'span.txt_sale')
        sale = sale_elem[0].text if sale_elem else '할인 없음'
        
        review_elem = book.find_elements(By.CSS_SELECTOR, 'span.rating_grade em.yes_b')
        review = review_elem[0].text if review_elem else '리뷰 없음'
        sales_volume = book.find_element(By.CSS_SELECTOR, 'span.saleNum').text
        
        tag_elem = book.find_elements(By.CSS_SELECTOR, 'span.tag')
        tag = ', '.join([t.text for t in tag_elem]) if tag_elem else '태그 없음'
        
        print(f"{i}. {title} | 저자 : {author} | 가격 : {cost} | 할인 : {sale}%")
        print(f" 리뷰 : {review}점 | {sales_volume}")
        print(f" 태그 : {tag}")

        total_count += 1

        b = {
            'title' : title,
            'author' : author,
            'cost' : cost,
            'review' : review,
            'sales_volume' : sales_volume,
            'sale' : sale,
            'tags' : tag
        }

        weekly_best.append(b)
    
    if total_count >= 30:
        break
driver.quit()
print("="*40 + "\n" f"총 {total_count}건 수집이 완료되었습니다!")

주간베스트 '1'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. 인생 마지막에 쓰는 주식투자 교과서 | 저자 : 정규준 저 | 가격 : 22,500 | 할인 : 10%%
 리뷰 : 10.0점 | 판매지수 136,137 |
 태그 : #투자심리, #개미일기, #주식투자입문, #슈퍼개미
2. 나의 완벽한 장례식 | 저자 : 조현선 저 | 가격 : 17,100 | 할인 : 10%%
 리뷰 : 9.6점 | 판매지수 249,495 |
 태그 : #출퇴근길완독도전
3. 괴테는 모든 것을 말했다 | 저자 : 스즈키 유이 저/이지수 역 | 가격 : 15,300 | 할인 : 10%%
 리뷰 : 9.0점 | 판매지수 415,983 |
 태그 : #이달의굿즈, #새해나의첫책, #이동진의올해의책, #이동진의이달의책, #문학적이면서도진보적인
4. 인생을 위한 최소한의 생각 | 저자 : 신영준, 고영성 저 | 가격 : 17,820 | 할인 : 10%%
 리뷰 : 9.6점 | 판매지수 225,045 |
 태그 : #교양을쌓을교양, #가볍게교양쌓기, #1일1교양
5. 2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상 | 저자 : 최태성 저 | 가격 : 17,100 | 할인 : 10%%
 리뷰 : 9.9점 | 판매지수 325,254 |
 태그 : #분철, #한능검심화, #한능검
6. 진보를 위한 주식투자 | 저자 : 이광수 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 8.8점 | 판매지수 407,403 |
 태그 : #투자전략, #ETF투자, #주식투자입문, #크레마클럽에있어요, #주식매매법
7. ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC | 저자 : ETS 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.8점 | 판매지수 227,394 |
 태그 : #신유형반영, #연습을실전처럼, #단기간고득점, #너만알려줄게고득점비법, #기출이답이다
8. ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC | 저자 : ETS 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.9점 | 판매지수 210,771 |
 태그 : #신유형반영, #연습을실전처럼, #단기간고득점, #너만알려줄게고득점비법, #기출이답이다
9. 죽은 왕녀를 위한 파반느 (양장 특별판) | 저자 : 박민규 저 | 가격 : 18,000 | 할인 : 10%%
 리뷰 : 9.5점 | 판매지수 167,358 |
 태그 : #이달의굿즈, #사랑의형태, #영화드라마원작, #넷플릭스, #크레마클럽에있어요
10. 2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하 | 저자 : 최태성 저 | 가격 : 16,650 | 할인 : 10%%
 리뷰 : 10.0점 | 판매지수 293,382 |
 태그 : #한능검심화, #한능검, #분철
11. 엄마가 유령이 되었어! | 저자 : 노부미 글그림/이기웅 역 | 가격 : 10,800 | 할인 : 10%%
 리뷰 : 8.8점 | 판매지수 286,908 |
 태그 : #눈물버튼그림책, #엄마의사랑, #읽다보면눈물바다
12. 2026 문동균 한국사 D-30 문단속 모의고사 | 저자 : 문동균 편저 | 가격 : 14,400 | 할인 : 10%%
 리뷰 : 10.0점 | 판매지수 88,722 |
 태그 : #분철
13. 해커스 토익 기출 VOCA (보카) | 저자 : David Cho 저 | 가격 : 11,610 | 할인 : 10%%
 리뷰 : 9.6점 | 판매지수 331,122 |
 태그 : #분철, #토익초보추천, #토익보카, #신유형반영, #너도나도보는토익기본서
14. 노력의 배신 | 저자 : 최철 저 | 가격 : 17,550 | 할인 : 10%%
 리뷰 : 10.0점 | 판매지수 15,765 |
 태그 : #그래제본소
15. 자몽살구클럽 | 저자 : 한로로 저 | 가격 : 10,800 | 할인 : 10%%
 리뷰 : 9.2점 | 판매지수 314,157 |
 태그 : #죽음에관하여, #삶과죽음, #연예인작가
16. 부처님 말씀대로 살아보니 | 저자 : 토니 페르난도 저/강정선 역 | 가격 : 17,010 | 할인 : 10%%
 리뷰 : 9.8점 | 판매지수 108,147 |
 태그 : #이달의굿즈, #마음공부, #마음챙김, #마음다스리기, #마음의평화
17. 박곰희 연금 부자 수업 | 저자 : 박곰희 저 | 가격 : 18,900 | 할인 : 10%%
 리뷰 : 9.7점 | 판매지수 520,221 |
 태그 : #이달의굿즈, #은퇴준비, #경제적자유, #똑똑하게투자하기, #노후대비
18. 모순 | 저자 : 양귀자 저 | 가격 : 11,700 | 할인 : 10%%
 리뷰 : 9.6점 | 판매지수 495,468 |
 태그 : #책책책_책을읽읍시다, #예스미츠에소개된책, #스트레이키즈현진이읽은책, #내별의책장_스트레이키즈, #삶의의미
19. 김재우의 기본 동사 100 | 저자 : 김재우 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.4점 | 판매지수 83,553 |
 태그 : #분철, #영어는네이티브처럼, #유튜버의책
20. 돈의 방정식 | 저자 : 모건 하우절 저/박영준 역 | 가격 : 25,200 | 할인 : 10%%
 리뷰 : 9.4점 | 판매지수 170,127 |
 태그 : #이달의굿즈, #돈이란무엇인가, #돈관념, #돈을아십니까
21. 경매 100계명 제2부 | 저자 : 박홍기 저 | 가격 : 21,600 | 할인 : 10%%
 리뷰 : 10.0점 | 판매지수 55,767 |
 태그 : #경매공부, #투자전략, #똑똑하게투자하기
22. 자본주의 시대에서 살아남기 위한 최소한의 경제 공부 | 저자 : 백억남(김욱현) 저 | 가격 : 25,200 | 할인 : 10%%
 리뷰 : 9.6점 | 판매지수 183,684 |
 태그 : #내인생첫경제공부
23. 너를 아끼며 살아라 | 저자 : 나태주 저 | 가격 : 16,650 | 할인 : 10%%
 리뷰 : 9.8점 | 판매지수 276,306 |
 태그 : #마음이따뜻해지는이야기, #위로와응원, #시인에세이
24. 코스피 1만 넥스트 레벨 | 저자 : 박시동 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.4점 | 판매지수 93,906 |
 태그 : #주식투자
주간베스트 '2'번째 페이지 도서 정보 수집을 시작합니다.
========================================
1. 완벽한 원시인 | 저자 : 자청 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.7점 | 판매지수 75,693 |
 태그 : #교양을쌓을교양, #1일1교양
2. 세종의 나라 1 | 저자 : 김진명 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.7점 | 판매지수 64,710 |
 태그 : #집콕엔장편, #무아지경시간순삭
3. 싯다르타 | 저자 : 헤르만 헤세 저/박병덕 역 | 가격 : 7,200 | 할인 : 10%%
 리뷰 : 9.5점 | 판매지수 176,424 |
 태그 : #배송비채우기, #북클러버의선택
4. 2026 심우철 실전 동형 모의고사 Season 2 | 저자 : 심우철 저 | 가격 : 13,500 | 할인 : 10%%
 리뷰 : 9.9점 | 판매지수 97,893 |
 태그 : #이달의굿즈, #공무원영어
5. 최소한의 삼국지 | 저자 : 최태성 저/이성원 감수 | 가격 : 17,550 | 할인 : 10%%
 리뷰 : 9.8점 | 판매지수 302,397 |
 태그 : #고전읽기, #불멸의고전, #고전읽어주는책, #하룻밤에끝내는삼국지, #삼국지
6. 2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급) | 저자 : 최태성 저 | 가격 : 19,800 | 할인 : 10%%
 리뷰 : 9.9점 | 판매지수 182,529 |
 태그 : #분철, #한능검, #한능검심화
========================================
총 30건 수집이 완료되었습니다!

In [29]:
df_30 = pd.DataFrame(weekly_best)
df_30.index.name = 'No'
df_30.index += 1 
df_30.to_csv('weekly30.csv',encoding='utf-8-sig')
df_30.head()

,title,author,cost,review,sales_volume,sale,tags
No,,,,,,,
1,인생 마지막에 쓰는 주식투자 교과서,정규준 저,"22,500",10.0,"판매지수 136,137",10%,"#투자심리, #개미일기, #주식투자입문, #슈퍼개미"
2,나의 완벽한 장례식,조현선 저,"17,100",9.6,"판매지수 249,495",10%,#출퇴근길완독도전
3,괴테는 모든 것을 말했다,스즈키 유이 저/이지수 역,"15,300",9.0,"판매지수 415,983",10%,"#이달의굿즈, #새해나의첫책, #이동진의올해의책, #이동진의이달의책, #문학적이면서..."
4,인생을 위한 최소한의 생각,"신영준, 고영성 저","17,820",9.6,"판매지수 225,045",10%,"#교양을쌓을교양, #가볍게교양쌓기, #1일1교양"
5,"2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",최태성 저,"17,100",9.9,"판매지수 325,254",10%,"#분철, #한능검심화, #한능검"

In [39]:
print(type(tag_elem))

<class 'list'>